export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  REPORT_MONTH_NOT_ENDED: "REPORT_MONTH_NOT_ENDED",
  REPORT_ALREADY_ARCHIVED: "REPORT_ALREADY_ARCHIVED",
  ADJUSTMENT_REQUIRES_ARCHIVE: "ADJUSTMENT_REQUIRES_ARCHIVE"
} as const;
